### PR TITLE
Fix wait.py duplications and wrong class invocation.

### PR DESCRIPTION
**Pull request by jschmid1**
introduced in pr #1161

Signed-off-by: Joshua Schmid <jschmid@suse.de>

suse internal: 1104801

 [Bug 1104801 - L3: Exception: 'HealthCheck' object has no attribute 'just' during "deepsea stage run ceph.maintenance.upgrade"](https://trello.com/c/rkaTllDE/13-bug-1104801-l3-exception-healthcheck-object-has-no-attribute-just-during-deepsea-stage-run-cephmaintenanceupgrade)

-----------------

**Checklist:**
~- [ ] Added unittests and or functional tests~
~- [ ] Adapted documentation~
- [x] Referenced issues or internal bugtracker
- [x] Ran integration tests successfully ( trigger with @susebot run teuthology )

### CODE REVIEW

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
[Bug 1104801 - L3: Exception: 'HealthCheck' object has no attribute 'just' during "deepsea stage run ceph.maintenance.upgrade"](https://trello.com/c/rkaTllDE/13-bug-1104801-l3-exception-healthcheck-object-has-no-attribute-just-during-deepsea-stage-run-cephmaintenanceupgrade)

**Comment by jschmid1** [comment]
@susebot run teuthology

**Comment by jschmid1** [comment]
please review @alexandergraul @tserong

**Comment by jschmid1** [comment]
[Add test for PR#1273](https://trello.com/c/sA0Or9Xn/31-add-test-for-pr1273)
